// src/components/tabs/SituationTab.vue
<script setup lang="ts">
import GcCard from '../GcCard.vue'
import PointCards from '../PointCards.vue'
import useCombatParser from '@/composables/useCombatParser'
import { Frontline, GrandCompany } from '@/types'
import { getFrontlineNames } from '@/tools'
import { useStore } from '@/stores'

const store = useStore()
const {
  combatData,
  getGcPoint, getGcIncreaseSpeed,
  situationLockMsg,
  pointData,
} = useCombatParser()
</script>

<template>
  <div class="page-panel">
    <!-- 内容锁定遮罩 -->
    <div v-if="situationLockMsg" class="absolute inset-0 z-20 flex items-center justify-center backdrop-blur-sm bg-black/30">
      <div class="text-center text-white">
        <div class="text-4xl mb-2">⛓️🔒⛓️</div>
        <div class="text-2xl font-semibold">{{ situationLockMsg }}</div>
      </div>
    </div>

    <!-- 剩余点分 -->
    <div class="page-title">剩余点分</div>
    <div class="w-full grid grid-cols-3 gap-2">
      <GcCard
        v-for="company in GrandCompany"
        :key="company"
        :gc="company"
        :me="combatData.gc === company"
        :float-points="getGcPoint(company)"
        :increase-speed="getGcIncreaseSpeed(company)"
      />
    </div>

    <!-- 当前据点 -->
    <div class="page-title">当前据点</div>
    <div
      v-if="combatData.zone === Frontline.shatter"
      class="w-full text-[1.25rem] self-baseline text-white px-1 py-0.5 rounded bg-gray-400/90 border border-black/50"
    >
      暂不支持解析{{ getFrontlineNames(combatData.zone)[1] }}的当前据点数据。
    </div>
    <PointCards
      :points="pointData"
      :card-style="store.appConfig.situation_pointcard_style"
    />
  </div>
</template>

<style scoped>
</style>

// src/app/components/tabs/SituationTab.tsx
import { Button } from 'tdesign-react/lib/';
import { CopyIcon } from 'tdesign-icons-react';
import { GrandCompany, Frontline } from '../../types';
import { getFrontlineNames } from '@/app/tools';
import GcCard from '../GcCard';
import PageStyle from '@/app/page.module.css';
import { useOverlayData } from '../OverlayDataProvider';

const SituationTab: React.FC = () => {
  const {
    gc,
    zone,
    getGcPoint,
    getGcIncreaseSpeed,
    getPointCards,
    appConfig,
    handleCopySituation,
    lockSituationMsg
  } = useOverlayData();

  return (
    <div className={PageStyle.panel}>
      {lockSituationMsg() && (
        <div className="absolute inset-0 z-20 flex items-center justify-center backdrop-blur-sm bg-black/30">
          <div className="text-center text-white">
            <div className="text-4xl mb-2">⛓️🔒⛓️</div>
            <div className="text-2xl font-semibold">{lockSituationMsg()}</div>
          </div>
        </div>
      )}
      <div className={PageStyle.title}>剩余点分</div>
      <div className="w-full grid grid-cols-3 gap-2">
        {Object.values(GrandCompany).map(company => (
          <GcCard 
            key={company} 
            gc={company} 
            me={gc === company} 
            floatPoints={getGcPoint(company)} 
            increaseSpeed={getGcIncreaseSpeed(company)} 
          />
        ))}
      </div>
      <div className={PageStyle.title}>当前据点</div>
      {zone === Frontline.shatter && (
        <div className="w-full text-[1.25rem] self-baseline text-white px-1 py-0.5 rounded bg-gray-400/90 border border-black/50">
          暂不支持解析{getFrontlineNames(zone)[1]}的当前据点数据。
        </div>
      )}
      <div className="w-full flex flex-col gap-0.5">{getPointCards()}</div>
      <div className="fixed bottom-4 right-8 z-10">
        {!appConfig.hide_situation_copy_btn && (
          <Button
            size="large"
            shape="circle"
            theme="success"
            icon={<CopyIcon />}
            onClick={handleCopySituation}
          />
        )}
      </div>
    </div>
  );
};

export default SituationTab;
